@startuml
'https://plantuml.com/activity-diagram-beta

start
:Отримання запиту на розрахунок вартості (claimId);

:Отримання заявки (Claim);
:Визначення типу ремонту (repair_type);

:Отримання конфігурації ціноутворення
(PricingConfig);

:Отримання активних знижок клієнта;

partition "Розрахунок секцій" {

  fork
    :Розрахунок робіт (Labor);
    :Отримання журналу робіт;
    :Обчислення фактичних годин;
    :Визначення тарифу за годину (labor_price_per_hour);

    if (Фактичний час < мінімального порогу?) then (так)
      :Застосування мінімального порогу оплати робіт;
    endif
    :Обчислення вартості робіт
    (години × labor_price_per_hour);
    :Формування позицій LABOR;
    :Застосування знижки;
  fork again
    :Розрахунок запчастин (Parts);
    :Отримання використаних запчастин;
    :Застосування коефіцієнта parts_coefficient;
    :Формування позицій PARTS;
    :Застосування знижки;
  fork again
    :Розрахунок доставки (Delivery);
    :Отримання доставок заявки;
    :Відбір доставок, що підлягають оплаті;
    :Обчислення вартості доставки;
    :Застосування коефіцієнта delivery_coefficient;
    :Формування позицій DELIVERY;
    :Застосування знижки;
  end fork

}

if (Тип ремонту = WARRANTY?) then (так)
  :Формування результату
  з нульовою підсумковою вартістю;
  :Збереження позицій робіт,
  запчастин та доставки
  як інформаційних;
else (ні)
  :Агрегація підсумкових сум
  з урахуванням знижок;
  :Обчислення загальної
  вартості рахунку;
endif


:Формування BillingResultDTO;
stop

@enduml
