@startuml
'https://plantuml.com/activity-diagram-beta

title Діаграма діяльності InvoiceService

start
:Отримання запиту\nна фінансову операцію;

if (Тип операції?) then (Створення рахунку)
  :Перевірка існування заявки;
  if (Заявка існує?) then (так)
    :Перевірка допустимості\nстворення рахунку;
    if (Дозволено?) then (так)
      :Створення рахунку\nу статусі DRAFT;
      :Збереження рахунку;
    else (ні)
      :Відмова у створенні рахунку;
      stop
    endif
  else (ні)
    :Помилка: заявка не знайдена;
    stop
  endif

elseif (Перерахунок рахунку)
  :Отримання рахунку;
  :Перевірка допустимості\nперерахунку;
  if (Дозволено?) then (так)
    :Отримання даних\nз BillingService;
    :Оновлення позицій рахунку;
    :Перерахунок підсумкових сум;
    :Збереження рахунку;
  else (ні)
    :Відмова у перерахунку;
    stop
  endif

elseif (Видача рахунку)
  :Отримання рахунку;
  :Перевірка статусу = DRAFT;
  if (Статус коректний?) then (так)
    :Перерахунок рахунку;
    if (Сума = 0?) then (так)
      :Встановлення статусу PAID;
      :Фіксація рахунку;
    else (ні)
      :Встановлення статусу ISSUED;
      :Встановлення строку оплати;
    endif
    :Збереження рахунку;
  else (ні)
    :Відмова у видачі рахунку;
    stop
  endif

endif

stop

@enduml
