spring.application.name=MediRepairTrack

spring.datasource.url=jdbc:mysql://localhost:3306/soapz_knt-22-2_zhadan
spring.datasource.username=root
spring.datasource.password=Ln12cVPZ_T+A9


spring.jpa.show-sql=true

# --- event and listeners ---
logging.level.ua.nure.medirepairtrack.Listener=INFO
logging.level.ua.nure.medirepairtrack.Event=INFO

#logging.level.org.springdoc=DEBUG
#logging.level.org.springframework.web=DEBUG
