spring.application.name=MediRepairTrack

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true

gemini.api.key=${GEMINI_API_KEY}

# --- event and listeners ---
logging.level.ua.nure.medirepairtrack.Listener=INFO
logging.level.ua.nure.medirepairtrack.Event=INFO

#logging.level.org.springdoc=DEBUG
#logging.level.org.springframework.web=DEBUG
