spring.application.name=MediRepairTrack

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true

gemini.api.key=${GEMINI_API_KEY}

# --- DSS similarity search ---
dss.similarity.top-k=10
dss.similarity.threshold=0.7


# --- DSS predicted works ---
dss.predicted-works.top-k=7
dss.predicted-works.min-probability=0.05

# --- DSS predicted work parts ---
dss.predicted-work-parts.top-k=10
dss.predicted-work-parts.min-probability=0.03

# --- DSS predicted defects ---
dss.predicted-defects.top-k=5
dss.predicted-defects.min-probability=0.10

# --- event and listeners ---
logging.level.ua.nure.medirepairtrack.Listener=INFO
logging.level.ua.nure.medirepairtrack.Event=INFO

#logging.level.org.springdoc=DEBUG
#logging.level.org.springframework.web=DEBUG
